# Generated by Django 5.2.8 on 2025-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uthor',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='AnonymousUser', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image/'),
        ),
    ]
