# Generated by Django 5.2.7 on 2025-10-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uthor',
            new_name='author',
        ),
    ]
