# Generated by Django 5.2.8 on 2025-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_uthor_post_author_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='키 별칭', max_length=50)),
                ('key', models.CharField(help_text='실제로 입력할 보안키 문자열', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
