# Generated by Django 5.2.7 on 2025-10-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_uthor_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_image/default_error.png', upload_to='blog_image/%Y/%m/%d'),
        ),
    ]
