# Generated by Django 5.2.8 on 2025-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_securitykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitykey',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='securitykey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='securitykey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='securitykey',
            name='name',
        ),
        migrations.AddField(
            model_name='securitykey',
            name='label',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitykey',
            name='secret',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
